export * from './getTheCheapestProduct'
export * from './getReputationPoints'
export * from './getTheBestSellingProduct'
export * from './getTheBestStarQuantityProduct'
export * from './setPointsToProducts'
export * from './getRecommendedProduct'